spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&serverTimezone=UTC
    username: root
    password: 12541254
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

blog:
  information:
    title: DevPub
    subtitle: Рассказы разработчиков
    phone: +7 903 666-44-55
    email: mail@mail.ru
    copyright: Дмитрий Сергеев
    copyrightFrom: 2005
